Updated npm install dependencies
Reason For Change: Encountered error due to missing doc on installing NPM dependencies

Error : 
```
npm run start

> helloworld@0.0.1 start
> ts-node src/client/main.ts

/opt/homebrew/lib/node_modules/ts-node/src/index.ts:840
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6053: File '@tsconfig/recommended/tsconfig.json' not found.

    at createTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:840:12)
    at reportTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:844:19)
    at create (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:855:36)
    at register (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:563:15)
    at main (/opt/homebrew/lib/node_modules/ts-node/src/bin.ts:281:27)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/ts-node/src/bin.ts:539:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  diagnosticCodes: [ 6053 ]
}
```

Fix:
npm install --save-dev @tsconfig/recommended